fail workflow if matching vivarium branch can't be found within 20 iterations (#425)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,9 +45,14 @@ jobs:
         run: |
           vivarium_branch_name='main'
           branch_name_to_check=${branch_name}
+          iterations=0
           while [ "$branch_name_to_check" != "$vivarium_branch_name" ]
           do
             echo "Checking for vivarium branch: ${branch_name_to_check}"
+            if [ $iterations -gt 20 ]; then
+              echo "Could not find upstream branch"
+              exit 1
+            fi
             if
               git ls-remote --exit-code \
               --heads https://github.com/ihmeuw/vivarium.git ${branch_name_to_check} == "0"
@@ -65,6 +70,7 @@ jobs:
                 | sed 's/^origin\///' \
               )"
               git checkout ${branch_name_to_check}
+              iterations=$((iterations+1))
             fi
           done
           git checkout ${branch_name}
